# Generated by Django 3.0.3 on 2021-07-14 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_remove_post_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
